version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:80"
    environment:
      - APP_ENV=development
      - APP_BASE_URL=http://localhost:8080/
      - TZ=Asia/Jakarta
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=app
      - DB_PASS=app
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
    ports:
      - "33060:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: